---
version: "3.8"

services:
  librenms:
    image: projecttampah/librenms:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - librenms_data:/data
    restart: unless-stopped

  dispatcher:
    image: projecttampah/librenms:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - librenms_data:/data
    environment:
      - DISPATCHER_NODE_ID=dispatcher1
      - SIDECAR_DISPATCHER=1
    restart: unless-stopped

  syslogng:
    image: projecttampah/librenms:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "514:514/tcp"
      - "514:514/udp"
    volumes:
      - librenms_data:/data
    environment:
      - SIDECAR_SYSLOGNG=1
    restart: unless-stopped

  snmptrapd:
    image: projecttampah/librenms:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "162:162/tcp"
      - "162:162/udp"
    volumes:
      - librenms_data:/data
    env_file:
      - "./librenms.env"
    environment:
      - "SIDECAR_SNMPTRAPD=1"
    restart: unless-stopped
