---
version: "3.8"

services:
  rrdcached:
    # https://hub.docker.com/r/crazymax/rrdcached
    image: crazymax/rrdcached:1.7.2-r5
    volumes:
      - rrd_db:/data/db
      - rrd_journal:/data/journal
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - LOG_LEVEL=LOG_INFO
      - WRITE_TIMEOUT=1800
      - WRITE_JITTER=1800
      - WRITE_THREADS=4
      - FLUSH_DEAD_DATA_INTERVAL=3600
    restart: unless-stopped
